config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'tweets#index'
  resources :tweets do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def self.search(search)
    return Tweet.all unless search
    self.where('title LIKE(?)',"%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet, dependent: :destroy
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to tweet_path(params[:tweet_id])  }
      format.json
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user.id == current_user.id
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to tweet_path(params[:tweet_id])  }
        format.json
      end
    end
  end

  private
  def comment_params
    params.permit(:text, :tweet_id).merge(user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet, only: [:create, :destroy]
  def create
    @like = current_user.likes.create(like_params)

    respond_to do |format|
      format.html 
      format.js
    end
  end

  def destroy
    @like = Like.find_by(tweet_id: @tweet.id, user_id: current_user.id)
    @like.destroy
    respond_to do |format|
      format.html 
      format.js
    end
  end

  private
  
  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
  
  def like_params
    params.permit(:tweet_id)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: [:index, :show]

  def index
    @all_ranks = Tweet.find(Like.group(:tweet_id).order('count(tweet_id) desc').limit(3).pluck(:tweet_id))
    if params[:q] == nil
      @results = Tweet.search(params[:q]).includes(:user).page(params[:page]).per(9).order("created_at DESC")
    else
      @results = Tweet.search(params[:q]).includes(:user).order("created_at DESC")
    end
    respond_to do |format|
      format.html
      format.json
    end

  end

  def new
  end

  def create
    Tweet.create(image: tweet_params[:image], text: tweet_params[:text], title: tweet_params[:title], user_id: current_user.id)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.destroy
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.update(tweet_params)
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
    @like = Like.new
  end

  private
    def tweet_params
      params.permit(:image, :text, :title)
    end

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.page(params[:page]).per(8).order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ラーメン工房</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
  
    
    <%= yield %>

  </body>
</html>

app/views/likes/create.js.erb
$("#like-<%= @tweet.id %>").html("<%= j(render partial: 'tweets/like', locals: {tweet: @tweet}) %>");

app/views/likes/destroy.js.erb
$("#like-<%= @tweet.id %>").html("<%= j(render partial: 'tweets/like', locals: {tweet: @tweet}) %>");

app/views/tweets/_header.html.erb
<div class="png">
  <img src="https://www.777logos.com/logotype/data/9411061/png/512/1/?c=fb2a12f2d2a121a644851bf0cc7c3019&rk=805476">
  </div>
  <p class="sabtitle">〜あなたは美味しいラーメンを知っていますか？〜</p>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/tweets">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/tweets/new">投稿</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users/<%= current_user.id %>"><%= current_user.nickname %></a>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
    <%= form_with url:"/",method:"GET" do |f| %>
    <div class="form-inline my-2 my-lg-0">
      <%= f.text_field :q, class: "form-control mr-sm-2 search-resize search-input" %>
      <div class="btn btn-outline-success my-2 my-sm-0">Search</div>
    </div>
    <% end %>
  </div>
</nav>

app/views/tweets/_header2.html.erb
<div class="png">
  <img src="https://www.777logos.com/logotype/data/9411061/png/512/1/?c=fb2a12f2d2a121a644851bf0cc7c3019&rk=805476">
  </div>
  <p class="sabtitle">〜あなたは美味しいラーメンを知っていますか？〜</p>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/tweets">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/tweets/new">投稿</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users/<%= current_user.id %>"><%= current_user.nickname %></a>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
    </nav>

app/views/tweets/_like.html.erb
<% if current_user.likes.find_by(tweet_id: @tweet.id) %>
<div>
  <h3>いいね件数: <%= @tweet.likes.count %></h3>
  <%= link_to tweet_like_path(@tweet, current_user.likes.find_by(tweet_id: @tweet.id)), method: :delete ,remote: true  do%>
    <i class="far fa-heart fa-2x like-btn"></i>
    <% end %>
    <h3>いいねしたユーザー</h3>
    <% @tweet.liked_users.each do |user| %>
  <li id="<% user.id %>"><%= user.nickname %></li>
<% end %>
</div>
<% else %>
<div>
  <h3>いいね件数: <%= @tweet.likes.count %></h3>
  <%= link_to tweet_likes_path(@tweet,current_user.likes.build) ,method: :post ,remote: true do%>
    <i class="far fa-heart fa-2x unlike-btn"></i>
    <% end %>
    <h3>いいねしたユーザー</h3>
    <% @tweet.liked_users.each do |user| %>
  <li id="<% user.id %>"><%= user.nickname %></li>
<% end %>
</div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="card-group">
      <div class="card">
        <img class="card-img-top" src="<%= result.image %>" alt="Card image cap">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item"><%= link_to '詳細', "/tweets/#{result.id}", method: :get %></div>
            <% if user_signed_in? && current_user.id == result.user_id %>
            <div class="dropdown-item"><%= link_to '削除', "/tweets/#{result.id}", method: :delete %></div>
            <div class="dropdown-item"><%= link_to '編集', "/tweets/#{result.id}/edit", method: :get %></div>
            <% end %>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= result.title.truncate(14, omission: '...')%></h5>
          <p class="card-text"><%= result.text.truncate(30, omission: '...')%></p>
          <p class="card-text"><small class="text-muted">いいね数：<%= result.liked_users.count %></small></p>
          <p class="card-text"><small class="text-muted"><%= result.updated_at.strftime("%Y-%m-%d %H:%M") %> <%= result.user.nickname %></small></p>
        </div>
      </div>
    </div>

app/views/tweets/create.html.erb
<%= render partial: "header2" %>

<div class="finish shadow p-3 mb-5 bg-white rounded" >
  <h3>投稿が完了しました<h3>
  <h6><a href="/tweets">投稿一覧へ戻る</a><h6>
</div>

app/views/tweets/destroy.html.erb
<%= render partial: "header2" %>

<div class="finish shadow p-3 mb-5 bg-white rounded" >
  <h3>削除が完了しました<h3>
  <h6><a href="/tweets">投稿一覧へ戻る</a><h6>
</div>

app/views/tweets/edit.html.erb
<%= render partial: "header2" %>

<%= form_tag("/tweets/#{@tweet.id}", method: :patch ) do %>
  <h2 class="top">
    編集する
  </h2>
  <div class="form-group">
    <label for="exampleInputPassword1">Title</label>
    <input class="form-control col-10 form-resize" placeholder="Title" name="title" value="<%= @tweet.title %>">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Image</label>
    <input class="form-control col-10 form-resize" placeholder="Image Url" name="image" value="<%= @tweet.image %>">
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Text</label>
    <textarea class="form-control col-10 form-resize" id="exampleFormControlTextarea1" rows="6" name="text"><%= @tweet.text %></textarea>
  </div>
  <button type="submit" class="btn btn-primary btn-resize">Sent</button>
<% end %>
<div class="air"></div>

app/views/tweets/index.html.erb
<%= render partial: "header"%>

<%# スライドショー %>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://imgfp.hotp.jp/IMGH/16/22/P019901622/P019901622_480.jpg" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://icotto.k-img.com/system/press_images/000/372/534/206af60f41c6369c5b0649d4fe72984da212c078.jpeg?1510021269" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://news.walkerplus.com/article/189879/1137204_615.jpg" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<%# 投稿 %>
<div class="all row">
  <div class="left-contents">
  <h3 class="top-title">投稿一覧</h3>
  <% if @results.any? %>
  <% @results.each do |result| %>
    <%= render partial: "tweet", locals: { result: result } %>
    <% end %>
    <% end %>
    <div class="pagi"><%= paginate(@results) %></div>
  </div>
  <%# ランキング %>
  <div class="ranking">
  <h3>いいねランキング</h3>
    <% @all_ranks.each.with_index(1) do |tweet, i| %>
    <h5>第<%= i %>位</h5>
    <div class="card rank">
        <img class="card-img-top rank-top" src="<%= tweet.image %>" alt="Card image cap">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item"><%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %></div>
            <% if user_signed_in? && current_user.id == tweet.user_id %>
            <div class="dropdown-item"><%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %></div>
            <div class="dropdown-item"><%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %></div>
            <% end %>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= tweet.title.truncate(14, omission: '...')%></h5>
          <p class="card-text"><%= tweet.text.truncate(30, omission: '...') %></p>
          <p class="card-text"><small class="text-muted">いいね数：<%= tweet.liked_users.count %></small></p>
          <p class="card-text"><small class="text-muted"><%= tweet.updated_at.strftime("%Y-%m-%d %H:%M") %> <%= tweet.user.nickname %></small></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<footer class="under">
  <p>ラーメン工房 © Website️ 2019</p>
</footer>

app/views/tweets/new.html.erb
<%= render partial: "header2" %>

<%# 投稿フォーム %>
<div class="tweets-form">
<%= form_tag('/tweets', method: :post) do %>
  <div class="form-group group-resize">
    <label for="exampleInputPassword1">Title</label>
    <input class="form-control col-10 form-resize" placeholder="Title" name="title" value="なるとや">
  </div>
  <div class="form-group group-resize">
    <label for="exampleInputEmail1">Image</label>
    <input class="form-control col-10 form-resize" placeholder="Image Url" name="image" value="https://tblg.k-img.com/restaurant/images/Rvw/12559/320x320_rect_12559935.jpg">
  </div>
  <div class="form-group group-resize">
    <label for="exampleFormControlTextarea1">Text</label>
    <textarea class="form-control col-10 form-resize" id="exampleFormControlTextarea1" rows="6" name="text">「塩ラーメン」のスープは、透き通った美しい色合いです。魚介と塩の味がしっかりとしていながらも優しい味わい。</textarea>
  </div>
  <button type="submit" class="btn btn-primary btn-resize">Sent</button>
  <% end %>
  <div class="air"></div>
  </div>

app/views/tweets/show.html.erb
<%= render partial: "header2" %>

<div class="all-comment">
  <div class="details">
    <div class="card-group">
      <div class="card">
        <img class="card-img-top" src="<%= @tweet.image %>" alt="Card image cap">
        <% if user_signed_in? && current_user.id == @tweet.user_id %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item"><%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %></div>
            <div class="dropdown-item"><%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %></div>
          </div>
        </div>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= @tweet.title %></h5>
          <p class="card-text"><%= @tweet.text %></p>
          <p class="card-text"><small class="text-muted"><%= @tweet.user.nickname %></small></p>
        </div>
      </div>
    </div>
  </div>
  
  <div class="iine" id="like-<%= @tweet.id %>">
  <% if current_user %>
  <%= render partial: "like", locals: { tweet: @tweet } %>
  <% end %>
  </div>
  <% if current_user %>
  <div class="comment-sent">
  <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post, id: "new_comment", data:{tweet: "#{@tweet.id}"}) do %>
  <div class="asd">
    <textarea class="form-control textbox" id="exampleFormControlTextarea1" rows="6" name="text" placeholder="コメントする"></textarea>
  </div>
  <button type="submit" class="btn btn-danger form__submit">Sent</button>
  <% end %>
  <% end %>
  <div class="comments">   
    <h4>＜コメント一覧＞</h4>
    <% if @comments %>
    <% @comments.each do |comment| %>
        <div class="comment_text" id="comment<%=comment.id%>">
        <div class="display">
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <% if user_signed_in? && current_user.id == comment.user_id %>
          <%= link_to '削除', "/tweets/#{@tweet.id}/comments/#{comment.id}", class:"delete" %>
        <% end %>
        </div>
          <div class="comment_mac">
          <%= comment.text %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="air"></div>
  </div>
</div>

app/views/tweets/update.html.erb
<%= render partial: "header2" %>

<div class="finish shadow p-3 mb-5 bg-white rounded" >
  <h3>更新が完了しました<h3>
  <h6><a href="/tweets">投稿一覧へ戻る</a><h6>
</div>

app/views/users/show.html.erb
<%= render partial: "tweets/header2" %>
 
<div class="all row" >
  <div class="nameran">
    <h3><%= @nickname %>さんの投稿一覧</p></h3>
    <% @tweets.each do |tweet| %>
    <div class="card-group">
      <div class="card">
        <img class="card-img-top" src="<%= tweet.image %>" alt="Card image cap">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item"><%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %></div>
            <% if user_signed_in? && current_user.id == tweet.user_id %>
            <div class="dropdown-item"><%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %></div>
            <div class="dropdown-item"><%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %></div>
            <% end %>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= tweet.title %></h5>
          <p class="card-text"><%= tweet.text %></p>
          <p class="card-text"><small class="text-muted">いいね数：<%= tweet.liked_users.count %></small></p>
          <p class="card-text"><small class="text-muted"><%= tweet.updated_at.strftime("%Y-%m-%d %H:%M") %></small></p>
        </div>
      </div>
    </div>
    <% end %>
    <%= paginate(@tweets) %>

  </div>